arooz/arooz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("user.urls", namespace="user"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
admin.site.site_header = "ecommerce Administration"
admin.site.site_title = "ecommerce Admin Portal"
admin.site.index_title = "Welcome to ecommerce Admin Portal"

arooz/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("about-us/", views.about_us, name="about_us"),
    path("blog-detail/", views.blog_detail, name="blog_detail"),
    path("blog-grid/", views.blog_grid, name="blog_grid"),
    path("blog-list/", views.blog_list, name="blog_list"),
    path("cart/<int:id>/", views.addtocart, name="addtocart"),
    path("cart/", views.viewcart, name="viewcart"),
    path("checkout/", views.checkout, name="checkout"),
    path("coming-soon/", views.coming_soon, name="coming_soon"),
    path("compare/", views.compare, name="compare"),
    path("contact-us/", views.contact_us, name="contact_us"),
    path("faq/", views.faq, name="faq"),
    path("forgot/", views.forget_password, name="forgot password"),
    path("change password/<token>/", views.change_password, name="change_password"),
    path("delete/<int:id>/", views.deletefromwishlist, name="deletefromwishlist"),
    path("deletecart/<int:id>/", views.deletefromcart, name="deletefromcart"),
    path("index-2/", views.index_2, name="index_2"),
    path("index-3/", views.index_3, name="index_3"),
    path("index-4/", views.index_4, name="index_4"),
    path("index-5/", views.index_5, name="index_5"),
    path("index-6/", views.index_6, name="index_6"),
    path("index-7/", views.index_7, name="index_7"),
    path("index-8/", views.index_8, name="index_8"),
    path("index-9/", views.index_9, name="index_9"),
    path("", views.index, name="index"),
    path("login/", views.login_views, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("order-success/", views.order_success, name="order_success"),
    path("order-tracking/", views.order_tracking, name="order_tracking"),
    path("otp/", views.otp, name="otp"),
    path("product-4-image/", views.product_4_image, name="product_4_image"),
    path("product-bottom-thumbnail", views.product_bottom_thumbnail, name="product_bottom_thumbnail"),
    path("product-bundle/", views.product_bundle, name="product_bundle"),
    path("product-left-thumbnail", views.product_left_thumbnail, name="product_left_thumbnail"),
    path("product-right-thumbnail", views.product_right_thumbnail, name="product_right_thumbnail"),
    path("product/<int:id>/", views.product, name="product"),
    path("product-sticky/", views.product_sticky, name="product_sticky"),
    path("search/", views.search, name="search"),
    path("seller-become/", views.seller_become, name="seller_become"),
    path("seller-dashboard/", views.seller_dashboard, name="seller_dashboard"),
    path("seller-detail-2/", views.seller_detail_2, name="seller_detail_2"),
    path("seller-detail/", views.seller_detail, name="seller_detail"),
    path("seller-grid-2/", views.seller_grid_2, name="seller_grid_2"),
    path("seller-grid/", views.seller_grid, name="seller_grid"),
    path("shop-banner/", views.shop_banner, name="shop_banner"),
    path("shop-category-slider/", views.shop_category_slider, name="shop_category_slider"),
    path("shop-category/<int:id>/", views.shop_category, name="shop_category"),
    path("shop/<int:id>/", views.shop, name="shop"),
    path("shop-list/", views.shop_list, name="shop_list"),
    path("shop-right-sidebar/", views.shop_right_sidebar, name="shop_right_sidebar"),
    path("shop-top-filter/", views.shop_top_filter, name="shop_top_filter"),
    path("sign-up/", views.sign_up, name="sign_up"),
    path("dashboard/", views.user_dashboard, name="dashboard"),
    path("wishlist/<int:id>/", views.addtowishlist, name="addtowishlist"),
    path("wishlist/", views.viewwishlist, name="viewwishlist"),
    path("404/", views.error_404, name="error_404"),
    path("whatsapp/", views.whatsappFun, name="whatsapp"),
    # custome measurements
    path("measurements/<int:id>/", views.measurements, name="measurements"),
    path("size/", views.size, name="size"),
    # cart add ajax
    path("addquantity/", views.addQuantity, name="addquantity"),
    path("lessquantity/", views.lessQuantity, name="lessquantity"),
    # event
    path("eventdate/", views.event, name="eventdate"),
]

arooz/templates/web/partials/footer.html
{% load static %}

<footer class="section-t-space">
    <div class="container-fluid-lg">
        <div class="service-section">
            <div class="row g-3">
                <div class="col-12">
                    <div class="service-contain">
                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/product.svg' %} "
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Every Fresh Products</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/delivery.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Free Delivery For Order Over $50</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/discount.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Daily Mega Discounts</h5>
                            </div>
                        </div>

                        <div class="service-box">
                            <div class="service-image">
                                <img src="{% static 'web/svg/market.svg' %}"
                                    class="blur-up lazyload" alt="">
                            </div>

                            <div class="service-detail">
                                <h5>Best Price On The Market</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="main-footer section-b-space section-t-space">
            <div class="row g-md-4 g-3">
                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-logo">
                        <div class="theme-logo">
                            <a href="/">
                                <img src="{% static 'web/images/logo/aroozlogo.jpeg' %}"
                                    class="blur-up lazyload" alt="">
                            </a>
                        </div>

                        <div class="footer-logo-contain">
                            <p>We are a friendly bar serving a variety of cocktails, wines and beers. Our bar is a
                                perfect place for a couple.</p>

                            <ul class="address">
                                <li>
                                    <i data-feather="home"></i>
                                    <a href="javascript:void(0)">Arooz Wedding Hub Malappuram </a>
                                </li>
                                <li>
                                    <i data-feather="mail"></i>
                                    <a href="javascript:void(0)">support@https://gedexo.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                 <!-- <div class="footer-title">
                        <h4>Categories</h4>
                    </div> 

                     <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="" class="text-content">Vegetables & Fruit</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Beverages</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Meats & Seafood</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Frozen Foods</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Biscuits & Snacks</a>
                            </li>
                            <li>
                                <a href="" class="text-content">Grocery & Staples</a>
                            </li>
                        </ul>
                    </div>  -->
                </div>

                <div class="col-xl col-lg-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Useful Links</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                            <li>
                                <a href="/" class="text-content">Home</a>
                            </li>
                            <li>
                                
                                <a href="/" class="text-content">Shop</a>
                            </li>
                          
                           
                            
                        </ul>
                    </div>
                </div>

                <div class="col-xl-2 col-sm-3">
                    <div class="footer-title">
                        <h4>Help Center</h4>
                    </div>

                    <div class="footer-contain">
                        <ul>
                           
                           
                           
                            <li>
                                <a href="{% url 'user:viewwishlist' %}" class="text-content">Your Wishlist</a>
                            </li>
                            <li>
                                <a href="{% url 'user:search' %}" class="text-content">Search</a>
                            </li>
                            <!-- <li>
                                <a href="{% url 'user:faq' %}" class="text-content">FAQ</a>
                            </li> -->
                        </ul>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-4 col-sm-6">
                    <div class="footer-title">
                        <h4>Contact Us</h4>
                    </div>

                    <div class="footer-contact">
                        <ul>
                            <li>
                                <div class="footer-number">
                                    <i data-feather="phone"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Hotline 24/7 :</h6>
                                        <h5>+91 888 104 2340</h5>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <div class="footer-number">
                                    <i data-feather="mail"></i>
                                    <div class="contact-number">
                                        <h6 class="text-content">Email Address :</h6>
                                        <h5>gedexohr@gmail.com</h5>
                                    </div>
                                </div>
                            </li>

                            <li class="social-app mb-0">
                                <h5 class="mb-2 text-content">Download App :</h5>
                                <ul>
                                    <li class="mb-0">
                                        <a href="https://play.google.com/store/apps" target="_blank">
                                            <img src="{% static 'web/images/playstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                    <li class="mb-0">
                                        <a href="https://www.apple.com/in/app-store/" target="_blank">
                                            <img src="{% static 'web/images/appstore.svg' %}"
                                                class="blur-up lazyload" alt="">
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="sub-footer section-small-space">
            <div class="reserve">
                <h6 class="text-content">©2022 gedexo All rights reserved</h6>
            </div>

            <div class="payment">
                <img src="{% static 'web/images/payment/1.png' %}"
                    class="blur-up lazyload" alt="">
            </div>

            <div class="social-link">
                <h6 class="text-content">Stay connected :</h6>
                <ul>
                    <li>
                        <a href="https://www.facebook.com/" target="_blank">
                          <i class="fa-brands fa-facebook"></i>
                            
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/" target="_blank">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/" target="_blank">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://in.pinterest.com/" target="_blank">
                            <i class="fa-brands fa-pinterest-p"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>