arooz/arooz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [path("admin/", admin.site.urls), path("", include("user.urls", namespace="user"))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)
admin.site.site_header = "ecommerce Administration"
admin.site.site_title = "ecommerce Admin Portal"
admin.site.index_title = "Welcome to ecommerce Admin Portal"

arooz/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("about-us/", views.about_us, name="about_us"),
    path("blog-detail/", views.blog_detail, name="blog_detail"),
    path("blog-grid/", views.blog_grid, name="blog_grid"),
    path("blog-list/", views.blog_list, name="blog_list"),
    path("cart/<int:id>/", views.addtocart, name="addtocart"),
    path("cart/", views.viewcart, name="viewcart"),
    path("checkout/", views.checkout, name="checkout"),
    path("coming-soon/", views.coming_soon, name="coming_soon"),
    path("compare/", views.compare, name="compare"),
    path("contact-us/", views.contact_us, name="contact_us"),
    path("faq/", views.faq, name="faq"),
    path("forgot/", views.forget_password, name="forgot password"),
    path("change password/<token>/", views.change_password, name="change_password"),
    path("delete/<int:id>/", views.deletefromwishlist, name="deletefromwishlist"),
    path("deletecart/<int:id>/", views.deletefromcart, name="deletefromcart"),
    path("index-2/", views.index_2, name="index_2"),
    path("index-3/", views.index_3, name="index_3"),
    path("index-4/", views.index_4, name="index_4"),
    path("index-5/", views.index_5, name="index_5"),
    path("index-6/", views.index_6, name="index_6"),
    path("index-7/", views.index_7, name="index_7"),
    path("index-8/", views.index_8, name="index_8"),
    path("index-9/", views.index_9, name="index_9"),
    path("", views.index, name="index"),
    path("login/", views.login_views, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("order-success/", views.order_success, name="order_success"),
    path("order-tracking/", views.order_tracking, name="order_tracking"),
    path("otp/", views.otp, name="otp"),
    path("product-4-image/", views.product_4_image, name="product_4_image"),
    path("product-bottom-thumbnail", views.product_bottom_thumbnail, name="product_bottom_thumbnail"),
    path("product-bundle/", views.product_bundle, name="product_bundle"),
    path("product-left-thumbnail", views.product_left_thumbnail, name="product_left_thumbnail"),
    path("product-right-thumbnail", views.product_right_thumbnail, name="product_right_thumbnail"),
    path("product/<int:id>/", views.product, name="product"),
    path("product-sticky/", views.product_sticky, name="product_sticky"),
    path("search/", views.search, name="search"),
    path("seller-become/", views.seller_become, name="seller_become"),
    path("seller-dashboard/", views.seller_dashboard, name="seller_dashboard"),
    path("seller-detail-2/", views.seller_detail_2, name="seller_detail_2"),
    path("seller-detail/", views.seller_detail, name="seller_detail"),
    path("seller-grid-2/", views.seller_grid_2, name="seller_grid_2"),
    path("seller-grid/", views.seller_grid, name="seller_grid"),
    path("shop-banner/", views.shop_banner, name="shop_banner"),
    path("shop-category-slider/", views.shop_category_slider, name="shop_category_slider"),
    path("shop-category/<int:id>/", views.shop_category, name="shop_category"),
    path("shop/<int:id>/", views.shop, name="shop"),
    path("shop-list/", views.shop_list, name="shop_list"),
    path("shop-right-sidebar/", views.shop_right_sidebar, name="shop_right_sidebar"),
    path("shop-top-filter/", views.shop_top_filter, name="shop_top_filter"),
    path("sign-up/", views.sign_up, name="sign_up"),
    path("dashboard/", views.user_dashboard, name="dashboard"),
    path("wishlist/<int:id>/", views.addtowishlist, name="addtowishlist"),
    path("wishlist/", views.viewwishlist, name="viewwishlist"),
    path("404/", views.error_404, name="error_404"),
    path("whatsapp/", views.whatsappFun, name="whatsapp"),
    # custome measurements
    path("measurements/<int:id>/", views.measurements, name="measurements"),
    path("size/", views.size, name="size"),
    # cart add ajax
    path("addquantity/", views.addQuantity, name="addquantity"),
    path("lessquantity/", views.lessQuantity, name="lessquantity"),
    # event
    path("eventdate/", views.event, name="eventdate"),
]

arooz/templates/web/login.html
{% extends 'web/partials/base2.html' %}

{% load static %}

{% block content %}
    <!-- Header End -->

    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="/">
                    <span class="material-symbols-outlined">
                        home
                        </span>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    <span class="material-symbols-outlined">
                        category
                        </span>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:search' %}" class="search-box">
                    <span class="material-symbols-outlined">
                        search
                        </span>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="{%url 'user:viewwishlist' %}">
                    <span class="material-symbols-outlined">
                        favorite
                        </span>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewcart' %}">
                    <span class="material-symbols-outlined">
                        shopping_cart
                        </span>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2 class="mb-2">Log In</h2>
                        <nav>
                            <!-- <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="/">
                                        <i class="fa fa-2x fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active">Log In</li>
                            </ol> -->
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain">
                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/log-in.png"
                            class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To Arooz Wedding Hub</h3>
                            <h4>Log In Your Account</h4>
                        </div>

                        <div class="input-box">               
                            <form class="row g-4" method="POST">
                                {% csrf_token %}
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input type="text" class="form-control" id="username" name="uname" placeholder="Phone Number">
                                        <label for="phone_number">Username</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input type="text" class="form-control" id="password" name="pass" placeholder="Password">
                                        <label for="phone_number">Password</label>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="forgot-box">
                                        
                                        <a href= "{% url 'user:forgot password'  %}" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">Log
                                        In</button>
                                </div>
                            </form>
                        </div>

                        <div class="other-log-in">
                            <h6>or</h6>
                        </div>

                        <div class="sign-up-box">
                            <h4>Don't have an account?</h4>
                            <a href="user:checkout">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->

    <!-- Footer Section Start -->
   
    <!-- Footer Section End -->

  

    <!-- Bg overlay Start -->
    <div class="bg-overlay"></div>
    <!-- Bg overlay End -->

    <!-- latest jquery-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/popper.min.js"></script>

    <!-- feather icon js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather-icon.js"></script>

    <!-- Slick js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick-animation.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/custom_slick.js"></script>

    <!-- Lazyload Js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/lazysizes.min.js"></script>

    <!-- script js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/script.js"></script>

    <!-- thme setting js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/theme-setting.js"></script>
</body>


<!-- Mon, 07 Nov 2022 10:09:26 GMT -->

</html>

{% endblock %}

arooz/templates/web/sign-up.html
{% extends 'web/partials/base2.html' %}

{% load static %}

{% block content %}

    <!-- mobile fix menu start -->
    <div class="mobile-menu d-md-none d-block mobile-cart">
        <ul>
            <li class="active">
                <a href="/">
                    <span class="material-symbols-outlined">
                        home
                        </span>
                    <span>Home</span>
                </a>
            </li>

            <li class="mobile-category">
                <a href="javascript:void(0)">
                    <span class="material-symbols-outlined">
                        category
                        </span>
                    <span>Category</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:search' %}" class="search-box">
                    <span class="material-symbols-outlined">
                        search
                        </span>
                    <span>Search</span>
                </a>
            </li>

            <li>
                <a href="{%url 'user:viewwishlist' %}">
                    <span class="material-symbols-outlined">
                        favorite
                        </span>
                    <span>My Wish</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:viewcart' %}">
                    <span class="material-symbols-outlined">
                        shopping_cart
                        </span>
                    <span>Cart</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- mobile fix menu end -->

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2>Sign In</h2>
                        <nav>
                            <!-- <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="/">
                                        <i class="fa fa-2x fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active">Sign In</li>
                            </ol> -->
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- log in section start -->
    <section class="log-in-section section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 d-lg-block d-none ms-auto">
                    <div class="image-contain">
                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/sign-up.png"
                            class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h3>Welcome To Fastkart</h3>
                            <h4>Create New Account</h4>
                        </div>

                        <div class="input-box">
                            <form class="row g-4" method="POST">
                                {% csrf_token %}
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                        <input type="text" class="form-control" name="fullname" placeholder="Full Name">
                                        {% comment %} {{user_form.customer_name}} {% endcomment %}
                                        <label for="fullname">Full Name</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                        <input type="email" class="form-control" name="email" placeholder="Email Address">
                                        {% comment %} {{user_form.email}} {% endcomment %}
                                        <label for="email">Email Address</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                        <input type="text" class="form-control" name="number" placeholder="Phone Number">
                                        {% comment %} {{user_form.phone_number}} {% endcomment %}
                                        <label for="number">Phone Number</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                        <input type="text" class="form-control" name="address" placeholder="Address">
                                        {% comment %} {{user_form.address}} {% endcomment %}
                                        <label for="Address">Address</label>
                                    </div>
                                </div>

                               


                               

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                        <input type="password" class="form-control" name="password"
                                            placeholder="Password">
                                            {% comment %} {{login_form.password1}} {% endcomment %}
                                        <label for="password">Password</label>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-floating theme-form-floating">
                                         <input type="password" class="form-control" name="password2"
                                            placeholder="Confirm Password"> 
                                             {% comment %} {{login_form.password2}}  {% endcomment %}
                                            <label for="password2">Confirm Password</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-info">
                                                    {{message}}
                                        </div>
                                    {% endfor %}
                                    {% endif %}
                                </div>

                                <div class="col-12">
                                    <button class="btn btn-animation w-100" type="submit">Sign Up</button>
                                </div>
                            </form>
                        </div>

                        <div class="other-log-in">
                            <h6>or</h6>
                        </div>

                        <div class="log-in-button">
                            <ul>
                                <li>
                                    <a href="https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&amp;flowEntry=ServiceLogin"
                                        class="btn google-button w-100">
                                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/google.png"
                                            class="blur-up lazyload" alt="">
                                        Sign up with Google
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/" class="btn google-button w-100">
                                        <img src="https://themes.pixelstrap.com/fastkart/assets/images/inner-page/facebook.png"
                                            class="blur-up lazyload" alt=""> Sign up with Facebook
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="other-log-in">
                            <h6></h6>
                        </div>

                        <div class="sign-up-box">
                            <h4>Already have an account?</h4>
                            <a href="login">Log In</a>
                        </div>
                    </div>
                </div>

                <div class="col-xxl-7 col-xl-6 col-lg-6"></div>
            </div>
        </div>
    </section>
    <!-- log in section end -->

    <!-- Tap to top start -->
    <div class="theme-option">
        <div class="setting-box">
          
            

            <div class="theme-setting-2">
                <div class="theme-box">
                    <ul>
                        <li>
                            <div class="setting-name">
                                <h4>Color</h4>
                            </div>
                            <div class="theme-setting-button color-picker">
                                <form class="form-control">
                                    <label for="colorPick" class="form-label mb-0">Theme Color</label>
                                    <input type="color" class="form-control form-control-color" id="colorPick"
                                        value="#0da487" title="Choose your color">
                                </form>
                            </div>
                        </li>

                        <li>
                            <div class="setting-name">
                                <h4>Dark</h4>
                            </div>
                            <div class="theme-setting-button">
                                <button class="btn btn-2 outline" id="darkButton">Dark</button>
                                <button class="btn btn-2 unline" id="lightButton">Light</button>
                            </div>
                        </li>

                        <li>
                            <div class="setting-name">
                                <h4>RTL</h4>
                            </div>
                            <div class="theme-setting-button rtl">
                                <button class="btn btn-2 rtl-unline">LTR</button>
                                <button class="btn btn-2 rtl-outline">RTL</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="back-to-top">
            <a id="back-to-top" href="#">
                <i class="fas fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <!-- Tap to top end -->

    <!-- Bg overlay Start -->
    <div class="bg-overlay"></div>
    <!-- Bg overlay End -->

    <!-- latest jquery-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/bootstrap/popper.min.js"></script>

    <!-- feather icon js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/feather/feather-icon.js"></script>

    <!-- Slick js-->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/slick-animation.min.js"></script>
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/slick/custom_slick.js"></script>

    <!-- Lazyload Js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/lazysizes.min.js"></script>

    <!-- script js -->
    <script src="https://themes.pixelstrap.com/fastkart/assets/js/script.js"></script>
</body>


<!-- , Mon, 07 Nov 2022 10:09:26 GMT -->

</html>


{% endblock %}